version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lost_found_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: lost_found_uninorte
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lost_found_backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://admin:password123@db:5432/lost_found_uninorte?schema=public
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
